// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw35efqqNFTlK9enkj91ZAO3nNotsMvco',
    appId: '1:54755072490:web:f75e2a22fee49a45ddba93',
    messagingSenderId: '54755072490',
    projectId: 'evently-b3ecf',
    authDomain: 'evently-b3ecf.firebaseapp.com',
    storageBucket: 'evently-b3ecf.firebasestorage.app',
    measurementId: 'G-20BH4MLV4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuwIvRmWRE1X3TsVJoBQSJ1Y4hyzwKGAg',
    appId: '1:54755072490:android:86de29cbcb247a78ddba93',
    messagingSenderId: '54755072490',
    projectId: 'evently-b3ecf',
    storageBucket: 'evently-b3ecf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTqaQskYG0htytYYfIlKN8Z2o_fxPlXKA',
    appId: '1:54755072490:ios:463fac5eb1ca71f5ddba93',
    messagingSenderId: '54755072490',
    projectId: 'evently-b3ecf',
    storageBucket: 'evently-b3ecf.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTqaQskYG0htytYYfIlKN8Z2o_fxPlXKA',
    appId: '1:54755072490:ios:463fac5eb1ca71f5ddba93',
    messagingSenderId: '54755072490',
    projectId: 'evently-b3ecf',
    storageBucket: 'evently-b3ecf.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw35efqqNFTlK9enkj91ZAO3nNotsMvco',
    appId: '1:54755072490:web:fae0c44bad94bff8ddba93',
    messagingSenderId: '54755072490',
    projectId: 'evently-b3ecf',
    authDomain: 'evently-b3ecf.firebaseapp.com',
    storageBucket: 'evently-b3ecf.firebasestorage.app',
    measurementId: 'G-T0P9PHQVEZ',
  );
}
